os:
  - linux

language: go
go:
  - 1.8

script:
  - TEST_FLAGS='-v -coverprofile=coverage.txt -covermode=atomic' make -e test
  - make test-sample

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $GOPATH/src/gx
