sudo: required
language: go
go:
- 1.8.x
- 1.9.x
env:
  global:
  - secure: R2/THCRt0p/5XR7vcYg77fNk2vLuBGcNIfu7/a47BxVREYUkAqHK2MpG6x9TbbUPnJksEpXeXHH3OVVyK7Q+QsNX6dcOfl15DBafJHlMbfMTJWGDm+pBhNLFSKtA3DRnyOTR/ZpN+xnN7A0TSl/WB+PNxX4TjZtFTAaVtZpVbK6Ins6pHylVh00biLVyZ/W2AowCqiM95Yt4SfnybHn8KApJ/orjbtlJL1+2qQa+rF5N625/pDDf4MF/CLbdODlKPJ1M704/Kq3mo4KgutL0xFPxI3hDPO6LwWdW/izmcfEP56J3UpuXbcnDwSgS6ieAH7gDjBZGC/BYp7IoZrvjLCUuL6QSefWm1G/NJZuL2J1PInHF8kKnvm6/bFkAcRNByVSsdrgqwjQUkHZ/1FP+OMEDFWZk1bRXt8nHsIa0VbmyM+7cn5sCgCIIEsBJbbyQA40eGk0BkCWBbqCrb1shSEYvYBM44CBZHuMIvpp0BfX9Fl5gM1XW0FfzUXw5lBmi6/JWy7DDAL0axkmFe3abq7vmWHUQybEW295UuUDvDO8ioTGYMWf5LLKs02nxIZIuccEdozlO1vohkucYpKamjZu/YcR0den7eHMxzU/dmTK8qZjKhQ6aOH/1xLpeCSE2fG5sHVT+0uQe/4p2Bq4QbF/ljk6kujUc4jlK6NIwg/g=
  - secure: KU/2msclYm1J9KQidXgRl63uEYev7op/kr5w37KNJaCTqmYUHk/090+4SQmEFf0csHNCeyqmHD4tTHQ4oKsIsmfmuC4EQkEmBvwBbQVT9+lmWM1cuHRZRnSudDa4UT36OVLc+iyR2wkTYcaDan6ZaYmd9tDW8pfyOP7TxH3rf/9TqACnKKjMeHyINxgijTqiSGNnBQaNyTiBa/y/60Eg78eqq3zVPZKkae6dqAJtHqrFJTLbE4rlfHcrkmYsZhUIcyXAzw/+elz4gKC4llPXQ9mpxruBJxI+LVOoFmaqTdXpYa/Bsc9PteJOQQdecPWS0XkbV6T7Y44gAtlevsbyedSv0tmVniM4jXTnsMJ0f3gZzV5kXLM2A5rpw3gIkdqtg+a3GkVIy229Ljz1KH17o6nf1AAndqrh7wCOMXTHt1xxC+26vExnAIcyDQHpzx/Y4vmGUAhJJujIfh9Ld4YYdI2r9dP3i8N8qxFZyuQ9Lh3S1AMdIf5sBRTr6rPnZtU0UC5HYWxlGhfv7eWuMydUX2zLOmgHQXkY9/Jp+4YJ3H/Ge1qf8UtfhZBxMJM6sYdplNVpNE6NE1CemprPc7A2AotUdGlUFdGGuxLSat8tPlLe0wlf31EhdskSOf35fUJuVSJDxb4x4Flan0O42qKAgjRT+OVYB4R9/8MWQi/k8+Y=
services:
- docker
script:
- make hcdev
- TEST_FLAGS='-v -coverprofile=$(pkg_path)/coverage.txt -covermode=atomic' make -e test
cache:
  directories:
  - $GOPATH/src/gx
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "master" ]; then cd docker; docker build -t "holochain/holochain-proto" .; cd ..; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push holochain/holochain-proto; fi
- if [ "$TRAVIS_BRANCH" == "589-docker-updates" ]; then cd docker; docker build -t "holochain/holochain-proto:develop" .; cd ..; fi
- if [ "$TRAVIS_BRANCH" == "589-docker-updates" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push holochain/holochain-proto:develop; fi
