#!/bin/sh


syncDir="/runtime/cluster/sync"
[ -d "$syncDir" ] || mkdir $syncDir $> /dev/null

syncFile=$1

if ! ls $syncDir/$syncFile &> /dev/null ; then
  if ! ls $syncDir/$syncFile.* &> /dev/null ; then
    ls $syncDir
    echo "HC: sync: WARNING: There was never a sync file: $syncFile to begin with"
  fi
fi

while true
  do
    if ! ls $syncDir/$syncFile &> /dev/null; then
      if ! ls $syncDir/$syncFile.* &> /dev/null ; then
        echo "HC: $syncFile sync released"
        exit 0
      fi
    fi
    #echo "HC: sync waiting on $syncFile"
    sleep 0.1
  done