#!/bin/sh
syncDir="/runtime/cluster/sync"
[ -d "$syncDir" ] || mkdir $syncDir $> /dev/null

syncFile=$1

[ ! -f "$syncDir/$syncFile" ] && echo "HC: sync: WARNING: There was never a sync file: $syncFile to begin with"

while { [ -f "$syncDir/$syncFile" ] || [ -f "$syncDir/$syncFile.*" ] ; }
  do
    sleep 0.1
  done