FROM golang:alpine
MAINTAINER Gerry Gleason && Christopher Reay

RUN apk add --update \
  git \
  make \
  sudo \
&& rm -rf /var/cache/apk/*

RUN go get -v -d github.com/metacurrency/holochain \
&& make -C "${GOPATH}/src/github.com/metacurrency/holochain" \
&& rm -rf ${GOPATH}/pkg ${GOPATH}/src/* ${GOPATH}/bin/gx*

RUN adduser -D holochain \
&& addgroup holochain wheel \
&& sed -i -e'/%wheel ALL=(ALL) NOPASSWD/s/# //' /etc/sudoers
USER holochain

EXPOSE 3141
